spring.application.name=http-request-function-sample
spring.cloud.function.definition=uppercase|httpRequestFunction
spring.cloud.stream.function.bindings.uppercase|httpRequestFunction-in-0=input
spring.cloud.stream.function.bindings.uppercase|httpRequestFunction-out-0=output
